// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx1KJJJlTwO9W06m5OfydK_kcXNVPDKGA',
    appId: '1:103778805605:android:0aa904a9d069105c40a38c',
    messagingSenderId: '103778805605',
    projectId: 'tranchepay-7106f',
    storageBucket: 'tranchepay-7106f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxXFMo9ykvSLPzVd4vTi4ZksV83miir_8',
    appId: '1:103778805605:ios:b3f920358cc539a740a38c',
    messagingSenderId: '103778805605',
    projectId: 'tranchepay-7106f',
    storageBucket: 'tranchepay-7106f.appspot.com',
    androidClientId: '103778805605-g8r32jg9afeu4hfm9t5ne7tulgskr6ee.apps.googleusercontent.com',
    iosClientId: '103778805605-h7bm7erbl41eq2hkj0h21g3ucvrlkkgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.tranchepayMobile',
  );
}
