name: tranchepay_mobile
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  dio: ^4.0.6
  dio_cache_interceptor: ^3.3.1
  dio_http_cache: ^0.3.0
  pin_code_fields: ^7.4.0
  mask_text_input_formatter: ^2.4.0
  image_picker: ^0.8.6+1
  awesome_bottom_bar: ^1.2.2
  intl: ^0.18.0
  persistent_bottom_nav_bar: ^5.0.2
  sliding_up_panel: ^2.0.0+1
  pull_to_refresh: ^2.0.0
  url_launcher: ^6.1.9
  firebase_core: ^2.6.1
  firebase_messaging: ^14.2.4
  qr_flutter: ^4.0.0
  money_formatter: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - config/settings.json
    - assets/images/
    - assets/icons/
